spring.application.name=Ecomerce


spring.h2.console.enabled=true
spring.h2.datasource.url=jdbc:h2:mem:test

 


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create